### ISSUE TITLE
connect-eposerver : The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by AlexDBA012** [Kreloc/Posh-ePoAPI#2]
Hi

I get this error message 

when I try using connect-eposerver.

connect-eposerver : The request was aborted: Could not create SSL/TLS secure channel.

Any suggestions?

Alex

**Comment by tmayville** [comment]
Same issue I am seeing  - I'm trying a few others as well - one gives me an "error 1" , no idea why and this one.  Still not sure any are actually connecting yet.. ;)

**Comment by Kreloc** [comment]
Sorry about never responding to this. I kinda no longer work with this server so I basically had left this alone. Anyway, the below code is something that was in one of the first versions of Connect-ePoServer that adds a policy for certificates to your computer. I originally found it on Stackoverflow I believe, don't know why I didn't include the URL at the time. Anyway, this is the code:

```PowerShell
Try
{
    add-type @"
using System.Net;
using System.Security.Cryptography.X509Certificates;
public class TrustAllCertsPolicy : ICertificatePolicy {
public bool CheckValidationResult(
    ServicePoint srvPoint, X509Certificate certificate,
    WebRequest request, int certificateProblem) {
    return true;
}
}
"@
    [System.Net.ServicePointManager]::CertificatePolicy = New-Object TrustAllCertsPolicy
}
Catch
{
    Write-Warning "TrustAllCertsPolicy already exists"
}    
```

This was in my code at one point due to this error before we changed something about the certificate the McAfee ePoServer was using. Try adding that to the begin block of the Connect-ePoServer function.

**Comment by Kreloc** [comment]
I revisited this issue and found I was getting the same error in my environment today.
The above does not need to be done for it to work. Two things are needed.
One is that the certificate authority used for the signing certificate for the mcafee website needs to be in the computer running this module's Trusted Root Certifciation Authorirty.
Two is to add one line of code to the Connect-ePoServer function in the module in the begin code block.

```PowerShell
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
```

After performing both of those, the connection was able to be made and the rest of the module works properly.
